# AppVeyor configuration file
# For more details see https://www.appveyor.com/docs/build-configuration/

# Call on gradle to build and run tests
build_script:
  - gradlew.bat assemble checkstyleMain checkstyleTest

test_script:
  - xunit.console.clr4 "C:\projects\plantumlstudio\Tests.Unit\bin\Package\Tests.Unit.dll"

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11  # Use 64-bit Java
